############################## ALIASES | CRIS-MUR #############################

alias emacs='emacs -nw'
alias glog='~/settings_linux/scripts/./git_log.sh'
alias gcc='gcc -Wall -pedantic -Werror -Wextra'
alias js-bang='echo "#!/usr/bin/node" | tee *.js'
alias bsh-bang='echo "#!/usr/bin/bash" | tee *.sh'
alias py-bang='echo "#!/usr/bin/python3" | tee *.py'
alias envy-bsh='echo "#!/usr/bin/env bash" | tee *.sh'
alias sts='git status'
alias daily='cat $HOME/daily'
alias t='tree -aI "node_modules|.git"'
alias mv='mv -iv'
alias cp='cp -riv'
alias mkdir='mkdir -pv'
alias dnc='dotnet new console -o'
alias br='dotnet build && dotnet run'
