#!/bin/bash

options=("Iniciar servicio" "Detener servicio" "Reiniciar servicio" "Salir")
selected=0

while true; do
    clear
    echo "=== Menú Interactivo ==="
    echo

    for i in "${!options[@]}"; do
        if [[ $i == $selected ]]; then
            tput setaf 6; tput bold
            echo "> ${options[$i]}"
            tput sgr0
        else
            echo "  ${options[$i]}"
        fi
    done

    read -rsn1 input
    case $input in
        A) ((selected--));;  # Flecha arriba
        B) ((selected++));;  # Flecha abajo
        "")  # Enter
            case $selected in
                0) echo "🔵 Iniciando servicio..."; sleep 1 ;;
                1) echo "🔴 Deteniendo servicio..."; sleep 1 ;;
                2) echo "🟡 Reiniciando servicio..."; sleep 1 ;;
                3) echo "👋 Saliendo..."; exit ;;
            esac;;
    esac

    ((selected < 0)) && selected=0
    ((selected >= ${#options[@]})) && selected=$((${#options[@]} - 1))
done

